stages:
  data_generation:
    cmd: python3 src/generate_all_data.py
    deps:
      - src/config/filepaths_constants.py
      - src/utils/data_processing.py
      - src/utils/visualization.py
      - src/utils/saving_reading_data.py
    outs:
      - data/regular_data.pkl:
          persist: true
      - data/transformed_data.pkl:
          persist: true
  data_prep:
    cmd: python3 src/data_prep.py
    deps:
      - src/generate_all_data.py
      - data/regular_data.pkl
      - src/utils/data_processing.py
      - src/config/filepaths_constants.py
      - src/config/data_constants.py
      - src/data_prep.py
      - src/utils/saving_reading_data.py
      - src/utils/visualization.py
    outs:
      - data/dicts/test_dict.pkl:
          persist: true
      - data/dicts/train_dict.pkl:
          persist: true
      - data/dicts/validation_dict.pkl:
          persist: true
      - data/model_io/test_x.pkl:
          persist: true
      - data/model_io/test_y.pkl:
          persist: true
      - data/model_io/train_x.pkl:
          persist: true
      - data/model_io/train_y.pkl:
          persist: true
      - data/model_io/validation_x.pkl:
          persist: true
      - data/model_io/validation_y.pkl:
          persist: true
      - data/transformations/input_transformations.pkl:
          persist: true
      - data/transformations/output_transformations.pkl:
          persist: true
      - data/model_io/validation_target.pkl:
          persist: true
      - data/model_io/train_target.pkl:
          persist: true
      - data/model_io/test_target.pkl:
          persist: true
    metrics:
      - metrics/data_param.json:
          cache: false
  train_model:
    cmd: python3 src/train.py
    deps:
      - data/dicts/train_dict.pkl
      - data/dicts/validation_dict.pkl
      - data/model_io/train_x.pkl
      - data/model_io/train_y.pkl
      - data/model_io/train_target.pkl
      - data/model_io/validation_x.pkl
      - data/model_io/validation_target.pkl
      - data/model_io/validation_y.pkl
      - data/regular_data.pkl
      - data/transformed_data.pkl
      - src/config/filepaths_constants.py
      - src/config/data_constants.py
      - src/config/model_constants.py
      - src/utils/data_processing.py
      - src/utils/dl_ds.py
      - src/arch/lstm_arch.py
      - src/utils/saving_reading_data.py
      - src/arch/seq2seq_arch.py
      - src/train.py
      - src/utils/visualization.py
    outs:
      - data/model/model.pkl
    metrics:
      - metrics/model_param.json:
          cache: false
      - metrics/train_metric.json:
          cache: false
  eval_model:
    cmd: python3 src/eval_model.py
    deps:
      - data/dicts/test_dict.pkl
      - data/model_io/test_x.pkl
      - data/model_io/test_target.pkl
      - data/model_io/test_y.pkl
      - data/regular_data.pkl
      - data/transformed_data.pkl
      - src/config/filepaths_constants.py
      - src/config/data_constants.py
      - src/config/model_constants.py
      - src/utils/data_processing.py
      - src/utils/dl_ds.py
      - src/utils/saving_reading_data.py
      - src/train.py
      - src/utils/visualization.py
      - data/model/model.pkl
    outs: